name: Deploy to staging

on:
  push:
    branches:
      - "main"

jobs:
  redeploy_frontend:
    name: Deploying frontend to staging server
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key

          ssh -o StrictHostKeyChecking=no -i ssh_key root@34.236.36.74 << 'EOF'
            cd deployOnAws
            git pull
            pnpm install
            pnpm run build
            pm2 restart http-backend
            pm2 restart web-app
            pm2 restart web-socket
          EOF